name: Publish
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - run: npm install
      - run: npm run build
      - run: |
          echo @mmdzov:https://npm.pkg.github.com/ > dist/.npmrc
          echo '//npm.pkg.github.com/:_authToken=${NPM_TOKEN}' >> dist/.npmrc
      - run: npm publish
        working-directory: ./dist
        env:
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}